=== tfreese/arser/arser-configuration/src/main/resources/xsd/arser-config.xsd
<?xml version="1.0" encoding="UTF-8"?>

<!-- https://www.w3schools.com/xml/schema_intro.asp -->

<!--<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">-->

<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
           xmlns="http://github.com/tfreese/arser/config"
           targetNamespace="http://github.com/tfreese/arser/config"
           attributeFormDefault="unqualified"
           elementFormDefault="qualified"
>

    <!--    <import schemaLocation="baseTypes.xsd" namespace="http://baseTypes" />-->

    <xs:element name="arser-settings">
        <xs:annotation>
            <xs:documentation source="description">Configuration for the ARtifact-SERvice.</xs:documentation>
        </xs:annotation>
        <xs:complexType>
            <xs:sequence>
                <xs:element name="workingDir" type="FileUri" />
                <xs:element name="server-setting" type="ServerSetting" />
                <xs:element name="http-client-setting" type="HttpClientSetting" />
                <xs:element name="repositories" type="Repositories" />
                <!--                <xs:element name="db-monitoring" type="DbMonitoringConfig" minOccurs="0" />-->
            </xs:sequence>
        </xs:complexType>
    </xs:element>

    <xs:complexType name="ServerSetting">
        <xs:sequence>
            <xs:element name="port">
                <xs:annotation>
                    <xs:documentation source="description">Port for the Server [1025-65534].</xs:documentation>
                </xs:annotation>
                <xs:simpleType>
                    <xs:restriction base="xs:positiveInteger">
                        <xs:minInclusive value="1025" />
                        <xs:maxInclusive value="65534" />
                    </xs:restriction>
                </xs:simpleType>
            </xs:element>
            <xs:element name="thread-pool-core-size" type="xs:positiveInteger" />
            <xs:element name="thread-pool-max-size" type="xs:positiveInteger" />
            <xs:element name="thread-name-pattern" type="xs:normalizedString" />
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="HttpClientSetting">
        <xs:sequence>
            <xs:element name="thread-pool-core-size" type="xs:positiveInteger" />
            <xs:element name="thread-pool-max-size" type="xs:positiveInteger" />
            <xs:element name="thread-name-pattern" type="xs:normalizedString" />
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="StoreSetting">
        <xs:annotation>
            <xs:documentation source="description">Configuration for caching a remote Repository</xs:documentation>
        </xs:annotation>
        <xs:sequence>
            <xs:element name="type">
                <xs:simpleType>
                    <xs:restriction base="xs:normalizedString">
                        <xs:enumeration value="file" />
                        <xs:enumeration value="jdbc" />
                    </xs:restriction>
                </xs:simpleType>
            </xs:element>
            <xs:element name="uri">
                <xs:simpleType>
                    <xs:restriction base="xs:anyURI">
                        <xs:minLength value="10" />
                    </xs:restriction>
                </xs:simpleType>
            </xs:element>
            <xs:element name="driverClassName" type="xs:normalizedString" minOccurs="0" />
            <xs:element name="user" type="xs:normalizedString" minOccurs="0" />
            <xs:element name="password" type="xs:normalizedString" minOccurs="0" />
            <xs:element name="pool-core-size" type="xs:positiveInteger" minOccurs="0" />
            <xs:element name="pool-max-size" type="xs:positiveInteger" minOccurs="0" />
        </xs:sequence>
    </xs:complexType>

    <xs:simpleType name="FileUri">
        <xs:annotation>
            <xs:documentation source="description">file://*</xs:documentation>
        </xs:annotation>
        <xs:restriction base="xs:anyURI">
            <xs:minLength value="10" />
            <xs:pattern value="file://.*" />
        </xs:restriction>
    </xs:simpleType>

    <xs:simpleType name="WebUri">
        <xs:annotation>
            <xs:documentation source="description">https://*, http://*</xs:documentation>
        </xs:annotation>
        <xs:restriction base="xs:anyURI">
            <xs:minLength value="10" />
            <xs:pattern value="https://.*" />
            <xs:pattern value="http://.*" />
        </xs:restriction>
    </xs:simpleType>

    <xs:simpleType name="ContextRoot">
        <xs:annotation>
            <xs:documentation source="description">ContextRoot of a Repository</xs:documentation>
        </xs:annotation>
        <xs:restriction base="xs:normalizedString">
            <xs:minLength value="5" />
            <xs:pattern value="([a-z0-9\-_])+" />
        </xs:restriction>
    </xs:simpleType>

    <xs:complexType name="FileRepoSetting">
        <xs:annotation>
            <xs:documentation source="description">File Repository [file://*].</xs:documentation>
        </xs:annotation>
        <xs:sequence>
            <xs:element name="contextRoot" type="ContextRoot" />
            <xs:element name="path" type="FileUri" />
        </xs:sequence>
        <!-- <xs:attribute name="writeable" type="xs:boolean" default="false"> -->
        <xs:attribute name="writeable" type="xs:boolean" use="required">
            <xs:annotation>
                <xs:documentation source="description">Use the Repository für deployments.</xs:documentation>
            </xs:annotation>
        </xs:attribute>
    </xs:complexType>

    <xs:complexType name="RemoteRepoSetting">
        <xs:annotation>
            <xs:documentation source="description">Remote Repository [https://*,http://*].</xs:documentation>
        </xs:annotation>
        <xs:sequence>
            <xs:element name="contextRoot" type="ContextRoot" />
            <xs:element name="uri" type="WebUri" />
            <xs:element name="storeSetting" type="StoreSetting" minOccurs="0" />
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="VirtualRepoSetting">
        <xs:annotation>
            <xs:documentation source="description">
                Virtual Repository as mirror [https://HOST:PORT/NAME]
                Processed in declarative order.
            </xs:documentation>
        </xs:annotation>
        <xs:sequence>
            <xs:element name="contextRoot" type="ContextRoot" />
            <xs:element name="repository-ref" type="xs:normalizedString" maxOccurs="unbounded" />
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="Repositories">
        <xs:annotation>
            <xs:documentation source="description">Repository Declaration.</xs:documentation>
        </xs:annotation>
        <xs:sequence>
            <xs:element name="remote" type="RemoteRepoSetting" maxOccurs="unbounded" />
            <xs:element name="file" type="FileRepoSetting" minOccurs="0" maxOccurs="unbounded" />
            <xs:element name="virtual" type="VirtualRepoSetting" maxOccurs="unbounded" />
        </xs:sequence>
    </xs:complexType>

    <!--    <xs:complexType name="DbMonitoringConfig">-->
    <!--        <xs:annotation>-->
    <!--            <xs:documentation source="description">DB-Monitoring for the Server.</xs:documentation>-->
    <!--        </xs:annotation>-->
    <!--        <xs:sequence>-->
    <!--            <xs:element name="jdbc-url">-->
    <!--                <xs:simpleType>-->
    <!--                    <xs:restriction base="xs:normalizedString">-->
    <!--                        <xs:minLength value="10" />-->
    <!--                        <xs:pattern value="jdbc:.*" />-->
    <!--                    </xs:restriction>-->
    <!--                </xs:simpleType>-->
    <!--            </xs:element>-->
    <!--        </xs:sequence>-->
    <!--        <xs:attribute name="enabled" type="xs:boolean" use="required">-->
    <!--            <xs:annotation>-->
    <!--                <xs:documentation source="description">Enable/Disable this service.</xs:documentation>-->
    <!--            </xs:annotation>-->
    <!--        </xs:attribute>-->
    <!--    </xs:complexType>-->

    <!--    <xs:simpleType name="RepositoryUri">-->
    <!--        <xs:annotation>-->
    <!--            <xs:documentation source="description">file://*, http://*, https://*</xs:documentation>-->
    <!--        </xs:annotation>-->
    <!--        &lt;!&ndash;        <xs:restriction base="xs:anyURI">&ndash;&gt;-->
    <!--        &lt;!&ndash;            <xs:pattern value="file://.*" />&ndash;&gt;-->
    <!--        &lt;!&ndash;            <xs:pattern value="http://.*" />&ndash;&gt;-->
    <!--        &lt;!&ndash;            <xs:pattern value="https://.*" />&ndash;&gt;-->
    <!--        &lt;!&ndash;        </xs:restriction>&ndash;&gt;-->
    <!--        <xs:union memberTypes="FileUri">-->
    <!--            <xs:simpleType>-->
    <!--                <xs:restriction base="xs:anyURI">-->
    <!--                    <xs:minLength value="10"/>-->
    <!--                    <xs:pattern value="http://.*"/>-->
    <!--                    <xs:pattern value="https://.*"/>-->
    <!--                </xs:restriction>-->
    <!--            </xs:simpleType>-->
    <!--        </xs:union>-->
    <!--    </xs:simpleType>-->

</xs:schema>

=== tfreese/arser/arser-application/src/main/resources/arser-config.xml
<?xml version="1.0" encoding="UTF-8"?>

<!-- https://www.w3schools.com/xml/schema_intro.asp -->

<!--<proxy-config xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="arser-config.xsd">-->
<!-- xsi:schemaLocation="http://github.com/tfreese/arser/config https://raw.githubusercontent.com/tfreese/arser/master/configuration/src/main/resources/xsd/arser-config.xsd" -->
<arser-settings xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns="http://github.com/tfreese/arser/config"
                xsi:schemaLocation="http://github.com/tfreese/arser/config https://raw.githubusercontent.com/tfreese/arser/master/configuration/src/main/resources/xsd/arser-config.xsd">

    <workingDir>file:///opt/jvmapps/arser</workingDir>

    <server-setting>
        <port>7999</port>
        <thread-pool-core-size>2</thread-pool-core-size>
        <thread-pool-max-size>6</thread-pool-max-size>
        <thread-name-pattern>http-server-%d</thread-name-pattern>
    </server-setting>

    <http-client-setting>
        <thread-pool-core-size>2</thread-pool-core-size>
        <thread-pool-max-size>6</thread-pool-max-size>
        <thread-name-pattern>http-client-%d</thread-name-pattern>
    </http-client-setting>

    <repositories>
        <remote>
            <contextRoot>maven-central</contextRoot>
            <uri>https://repo1.maven.org/maven2</uri>
        </remote>
        <remote>
            <contextRoot>spring-release</contextRoot>
            <uri>https://repo.spring.io/release</uri>
        </remote>
        <remote>
            <contextRoot>primefaces</contextRoot>
            <uri>https://repository.primefaces.org</uri>
            <storeSetting>
                <type>file</type>
                <uri>file:///opt/jvmapps/arser/cache/primefaces</uri>
            </storeSetting>
        </remote>
        <remote>
            <contextRoot>gradle-releases</contextRoot>
            <uri>https://repo.gradle.org/gradle/libs-releases</uri>
            <storeSetting>
                <type>jdbc</type>
                <uri>jdbc:hsqldb:file:/opt/jvmapps/arser/database/gradle-releases/gradle-releases;shutdown=true</uri>
                <driverClassName>org.hsqldb.jdbc.JDBCDriver</driverClassName>
                <user>sa</user>
                <password />
                <pool-core-size>2</pool-core-size>
                <pool-max-size>6</pool-max-size>
            </storeSetting>
        </remote>
        <remote>
            <contextRoot>gradle-plugins</contextRoot>
            <uri>https://plugins.gradle.org</uri>
        </remote>
        <local writeable="true">
            <contextRoot>third-party</contextRoot>
            <path>file:///home/tommy/.m2/third-party</path>
        </local>
        <local writeable="true">
            <contextRoot>deploy-releases</contextRoot>
            <path>file:///opt/jvmapps/arser/work/deploy-releases</path>
        </local>
        <local writeable="true">
            <contextRoot>deploy-snapshots</contextRoot>
            <path>file:///opt/jvmapps/arser/work/deploy-snapshots</path>
        </local>
        <local writeable="true">
            <contextRoot>deploy-sites</contextRoot>
            <path>file:///opt/jvmapps/arser/work/deploy-sites</path>
        </local>
        <virtual>
            <contextRoot>public</contextRoot>
            <repository-ref>maven-central</repository-ref>
            <repository-ref>spring-releases</repository-ref>
            <repository-ref>primefaces</repository-ref>
            <repository-ref>gradle-releases</repository-ref>
            <repository-ref>gradle-plugins</repository-ref>
        </virtual>
        <virtual>
            <contextRoot>public-local</contextRoot>
            <repository-ref>third-party</repository-ref>
            <repository-ref>deploy-releases</repository-ref>
            <repository-ref>deploy-snapshots</repository-ref>
        </virtual>
    </repositories>

</arser-settings>
